In [2]:
import tensorflow as tf
import numpy as np

In [122]:
arr = tf.constant(np.array([[-0.4, 0.1, 0.6, 1.1, 1.2], [0.1, 0.1, 0.1, 0.1, 0.1]]))
arr

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[-0.4,  0.1,  0.6,  1.1,  1.2],
       [ 0.1,  0.1,  0.1,  0.1,  0.1]])>

In [25]:
from keras.layers import Discretization, Flatten

In [188]:
boundaries = [0.0, 0.5, 1.0]
quant = Discretization(bin_boundaries=boundaries, output_mode="int")

In [220]:
quantized = quant(tf.abs(arr)) - 1
one_hot = to_categorical(quantized, num_classes=len(boundaries))
shape = [*one_hot.shape[:-2], int(tf.reduce_prod(one_hot.shape[-2:]))]
result = tf.reshape(one_hot, shape)

sign = tf.where(arr < 0, 1., 0.)
signed_result = tf.concat([sign, result], axis=1)
signed_result

<tf.Tensor: shape=(2, 20), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
        1., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
        0., 1., 0., 0.]], dtype=float32)>